spring.application.name=spring-data-jpa-practice

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=broadcom_db;encrypt=false;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=Password@123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

 management.endpoints.web.exposure.include=*

#provides comprehensive health check details like disk space, db status, etc.
management.endpoint.health.show-details=always

#group health indicators
#actuator/health/system
management.endpoint.health.group.system.include=diskSpace, db
#actuator/health/web
management.endpoint.health.group.web.include=ping